universe        = vanilla
executable      = x265
initialdir      = /home/workspace/zhenyu/x265-iframe-adpatinitqp-amortize-slicetye-decide-bpframeqp-cutreebpstrength-multicore-purcutreelog/build/linux/BasketballDrive_832x480_dst_18_2000
error           = BasketballDrive_832x480_dst_18_2000.error
log             = BasketballDrive_832x480_dst_18_2000.log
output          = BasketballDrive_832x480_dst_18_2000.output
notification    = error
should_transfer_files = YES
run_as_owner    = True
priority        = 10
arguments       = --pass 1 --preset veryslow --min-keyint 1 --input /home/video_sequence/cisq_database//BasketballDrive_832x480_dst_18.yuv --input-res 832x480 --fps 50 --ref 4 --frame-thread 1 --no-wpp --bitrate 2000 --no-pmode --no-pme --slices 0 --lookahead-slices 0 --psnr --tune psnr --qg-size 64 --b-adapt 2 --bframes 15 --keyint 5000 -o output-pass1.265
queue
